name: pointycastle
version: 1.1.1
author: The Bouncy Castle Team
description: A Dart library implementing cryptographic algorithms and primitives, modeled on the BouncyCastle library.
homepage: https://github.com/PointyCastle/pointycastle
environment:
  sdk: ">=2.2.0 <3.0.0"
#documentation: http://pointycastle.github.io/docs/

dev_dependencies:
  benchmark_harness: ">=1.0.5 <2.0.0"
  matcher: ">=0.12.0 <0.13.0"
  test: ">=0.12.30 <1.4.0"

